name: zpl2
description: "Send ZPL (Zebra Printing Language) commands to Zebra printers."
version: 0.1.1
repository: https://github.com/Apex-P/zpl2

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  custom_lint: ^0.7.0
