name: zpl2
description: "Send ZPL (Zebra Printing Language) commands to Zebra printers."
version: 0.2.5+0
repository: https://github.com/Apex-P/zpl2

environment:
  sdk: ^3.8.0
  flutter: "^1.17.0"

dependencies:
  decimal: ^3.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.8
  equatable_lint: ^0.3.0
